

#############################################################################################################################
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 033746436249.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_NAME="ecr"      
      - REPOSITORY_URI=033746436249.dkr.ecr.us-east-2.amazonaws.com/dockerfile1:latest
          
      
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t dockerfile1:latest -f ./file1/Dockerfile .
      - docker tag dockerfile1:latest 033746436249.dkr.ecr.us-east-2.amazonaws.com/dockerfile1:latest
      - docker build -t dockerfile2:latest -f ./file2/Dockerfile .
      - docker tag  dockerfile2:latest 033746436249.dkr.ecr.us-east-2.amazonaws.com/dockerfile2:latest   ###### change
      


      #- docker tag $REPOSITORY_NAME:latest $REPOSITORY_URI:$IMAGE_TAG


  post_build:
    commands:
      -  echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 033746436249.dkr.ecr.us-east-2.amazonaws.com/dockerfile1:latest
      - docker push 033746436249.dkr.ecr.us-east-2.amazonaws.com/dockerfile2:latest  ##### change
     
      
      #- docker push $REPOSITORY_URI:$IMAGE_TAG

      - echo Writing image definitions file...
     
      - echo Writing image definitions file...
      - printf '[{"name":"html1_container","imageUri":"033746436249.dkr.ecr.us-east-2.amazonaws.com/dockerfile1:latest"}]'  > imagedefinitions1.json
      - printf '[{"name":"html2_container","imageUri":"033746436249.dkr.ecr.us-east-2.amazonaws.com/dockerfile2:latest"}]'  > imagedefinitions2.json


artifacts:
  files: 
   
    - imagedefinitions1.json

    - imagedefinitions2.json

